//
//  DiaryCanvasViewModel.swift
//  Divary
//
//  Created by 김나영 on 7/22/25.
//

import Foundation
import PencilKit
import Combine
import SwiftUI

final class DiaryCanvasViewModel: ObservableObject {
    let canvas: PKCanvasView = PKCanvasView()
    let toolPicker: PKToolPicker = PKToolPicker()

    @Published var canUndo: Bool = false
    @Published var canRedo: Bool = false
    
    @Binding var showCanvas: Bool

    private var timer: Timer?

    init(showCanvas: Binding<Bool>) {
        _showCanvas = showCanvas
        startMonitoringUndoRedo()
    }

    deinit {
        timer?.invalidate()
    }

    func undo() {
        canvas.undoManager?.undo()
    }

    func redo() {
        canvas.undoManager?.redo()
    }

    func dismissCanvas() {
//        toolPicker.setVisible(!toolPicker.isVisible, forFirstResponder: canvas)
        toolPicker.setVisible(false, forFirstResponder: canvas)
        showCanvas = false
    }

    private func startMonitoringUndoRedo() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            guard let self else { return }
            canUndo = canvas.undoManager?.canUndo ?? false
            canRedo = canvas.undoManager?.canRedo ?? false
        }
    }
    // 스트링
    func saveDrawingAsString() -> String {
        let drawing = canvas.drawing
        let data = drawing.dataRepresentation()
        let base64String = data.base64EncodedString()
        return base64String
    }
    
    func loadDrawingFromString(_ base64String: String) {
        guard let data = Data(base64Encoded: base64String) else {
            print("base64 복호화 실패")
            return
        }
        
        do {
            let drawing = try PKDrawing(data: data)
            canvas.drawing = drawing
        } catch {
            print("PKDrawing 복원 실패: \(error.localizedDescription)")
        }
    }
    
    // 파일
    func saveDrawingToFile() {
        let drawing = canvas.drawing
        let data = drawing.dataRepresentation()
//        guard let data = JSONManager.shared.encode(codable: drawing) else {
//            return
//        }
        print(data.base64EncodedString())
        let url = drawingFileURL()

        do {
            try data.write(to: url)
            showCanvas = false
        } catch {
            print(error.localizedDescription)
        }
    }
    
    func loadDrawingFromFile() {
//        let pkDrawingString = "d3Jk8AEACAASEAAAAAAAAAAAAAAAAAAAAAASEBzfYxvbQ0OjuYPKtt9MvSQaBggAEAAYABoGCAQQARgEIjQKFA0AAAAAFQAAAAAdAAAAACUAAIA/EhFjb20uYXBwbGUuaW5rLnBlbhgDQQAAAAAAAOC/Kr0MChBN2f65vhBIyoOHpfG1jAHBEgYIABABGAEaBggAEAEYACAAKvkLChCRWZfDzRNFVIsB8H7ggG2tEcxEBzNAGcdBGFwgByj4BzIQ6AMAAAAAiiUAAP9/AACAPzrAC1VV+UKrqnhDAAAAAOkQS0BVVQFDq6p1Q+bKcD3pEEtAq6oOQwAAa0Nvgaw96RBLQJ4OFEO1WmZDJVvRPekQS0AAABxDq6pfQ8INCT7pEEtAq6ofQ6uqXEM4vR0+6RBLQAAAJUNVVVlDgq47PukQS0ByHClDHMdXQ9fSTD7pEEtAVVUtQ1VVVkNh110+6RBLQAAANEOrqlRDWVB0PukQS0Crqj5Dq6pRQ29Gij7pEEtAAABFQ1VVUUPuy5k+6RBLQAAASUMAAFJDuWyiPukQS0CrqkxDAABTQxjPqj7pEEtAAABSQ1VVV0NBnrM+6RBLQKuqVkNVVV1DHuy7PukQS0BVVVtDAABkQ52dxD7pEEtAq6pfQ6uqakM7CM0+6RBLQAAAZENVVXFDgZjVPukQS0BVVWdDq6p2Q8063j7pEEtAq6ppQ6uqfUMG2eY+6RBLQFVVa0NVVYJD9UfvPiA9T0CrqmxDAICLQxDq9z7o809AAABsQ1VVkUOIPQA/lOxPQKuqZ0NV1aBDG+YEP96tT0CrqmNDVVWnQy/9DD/pEEtAq6pfQ1XVqkPvqBE/6RBLQFVVXUNVVaxDFZ8XP+kQS0CrqlZDVdWtQ5SiHj/pEEtAAABMQ6sqrkPvRSc/6RBLQAAAMEMAgKtD9a8vP3awTUCrqhxDAACjQwqtNz8PKU5AAAAYQwAAnkOG9Ts/A8ZMQAAAFUMAAJlDKDpAP+FaTEBVVRRDq6qTQ+N+RD9bD0xAVVUUQ6sqj0NlOUk/UhVNQFVVIUNVVYVDBFhRPy5AUUCrqitDAACBQ4qTVT/Z/FJAAABEQwAAcEOs11k/VV9SQAAAT0NVVWtDZR1ePxMlVEBVVV5DVVVmQ2NhYj/XtlNAAABoQ1VVY0PgHWc/0yJPQFVVfUMAAFxDsIJrPz+iTUCrKodDq6pUQ/pvcz/pEEtAVdWJQ6uqUUPQxnc/6RBLQACAi0MAAE5DooN8P+kQS0AAAI1DVVVGQ4OPgT9hGUxAAACPQ6uqKkPwWIQ/4WxOQAAAj0OrqiJDJsGGP/TvUEAAgI1DAAALQ3/hiD9RlVFAVVWLQ6uqBEOWBos/wJdOQAAAfENVVelCvRGPP5VjTkAAAHhDAADkQgtBkT+gjk1AAABnQ1VVz0IuW5M/wKFLQFVVXkMAAMhCTnuVP039UEAAAFlDVVXFQl+hlz+zOlNAq6pRQ1VVw0IW+Jk/O3pRQKuqJkNVVdlCyhWcP/W/T0AAABBDq6rmQo9goD/+Z01AAAAOQ6uq5kLLbqQ/6RBLQCJSDUOWqulCJOWoP+kQS0AAAA1Dq6ryQqcWrT/pEEtAAAAMQwAAAkN0J68/cOFMQKuqC0MAABBD+4KxPzC2UkCrqgtDAAApQ06csz/C9lVAq6oMQ6uqOkM2wrU/wBJYQFVVE0OrqlVDCfG3P0CpWUCrqh9DVVVuQ8xNuj/8lFlAAABHQ6uqj0Orlr4/HyhZQFVVZ0NVVZ9DD97CP990VkAAgIBDqyqrQ5hBxz/QiVFAq6qIQwAAskPCOss/kLJcQKsqi0MAgLRDjXPNP7FaXEAAgIpDAADQQ8qhzz+4uVtAqyqIQ6sqBESf0dE/4QdbQFVVh0MAgAREvArWP+4AV0CrqoZDVdUERGBU2j/pEEtAq6p8Q6sqCES4aN4/6RBLQAAAckMAQApE2x/jP1hSTkBVVVJDVRUORM2e5j9pLE5AVVVDQ1XVDkS3++g/PqZPQKuqMUNV1Q5EV53tPyKrTUAAAB5Dq6oLRERJ8T+cu0xAAAAVQwAACERkofM/ZsxPQAAAEENVFQVEkdv1P0t3UECrqg5Dq+oDRHce+D8M+FJAAAAMQ1XV+kPEYvo/trtUQFVVDEOrKvRDKHD8P5h3U0BVVSNDq6reQ3A9AECw+FZAq6onQwCA3EMqgAFAJSpgQAAARkNV1dJDc1QDQILLYUBVVa5DVdWcQ5VjBEDMvWNAQAEyFA0AAPZCFQAAwEIdAABkQyUAgO5DQOClz77bBSqdAwoQcPXp2liATlSMHWNLbkY6nxIGCAEQARgCGgYIABABGAAgACrZAgoQd5Up93eTRgeBTk3vLvJ0XhHpRl40QBnHQRgSIAco+AcyEOgDAAAAAAAAAAD/fwAAgD86oAIAgMhDq6poQwAAAADQyFVAE1HEQ/Mqe0M/b4o8yn1VQHzWv0MLBoVDyTsHPXmVU0AeaLpDfG2NQ1RUTT36h1FA9XW1Q5tzlEP7WYg92iROQDkPs0PROZdDkDeqPfIdS0DadrBDYlqaQzrVzz3pEEtATwKuQ3hSnUMsYgg+6RBLQGhjrEOXjp9D6vsZPukQS0A1H6hDdR2nQ1hrOz7pEEtASu+lQx0Tq0NLW0w+6RBLQIvBo0PRIq9DVdtdPukQS0A8yaFDxceyQ+Unbz7GAVRAHZ2gQ6zxtENxBIA+zoZZQLiWn0N757ZDpHCIPp0oWUDoPotDScPzQymdmT7a71hAvwaKQ/z59kNYrqo+SehVQKuqiENVVfpD712zPukQS0BAATIUDQCAh0MVAABnQx0AAARDJQAAiENAwPWC/coFKr0FChCFtvo6A7BNlaTUq+U+6KrIEgYIAhABGAMaBggAEAEYACAAKvkEChBwljCxdlxDX5+51cKikNPaEWIvzDRAGcdBGCQgByj4BzIQ6AMAAAAAudcAAP9/AACAPzrABACApkMAAP1DAAAAAOkQS0AAgKNDVdX7QzNP6j0khlNAVdWYQwAA9EMfSAY+b1xXQKsqjkOrqupDCGEXPoQ/WkBVVXxDVdXdQ7JUKD7HlF1AVVVjQ1XV0kP+hzk+lXxdQKuqSUOrqsZDQYJKPkcoXkBVVR9DAACyQ/eaWz7lyV1Aq6oPQ6uqqENKuGw+6FVdQKuq7kIAgJdDqeR9PvayXEBVVclCAACIQzYZiD5ECFlAVVWjQquqZ0Orjpg+mDxTQAAAokIAAGZDM/GgPsa3TEBVVZ1Cq6peQzuNqT7pEEtAAACYQgAAWEOZLbI+6RBLQKuqlkKrqlRDi8O6PukQS0CrqpZCYpFQQ8WE1D7pEEtAq6qWQquqTkPGY+U+6RBLQHIcm0KO409DEfgUP+kQS0BVVZ9CVVVRQ1iMGj/pEEtAq6qwQlVVV0OexCE/Eg5MQFVVxUIAAF9DZOMmP4rqUUCrqgJDq6p0Q9SVLj+DqVZAq6oWQ1XVgUM26DI/wy5YQKuqKUMAgIlD65U3PzvNWEBVVUxDq6qaQ9KkPz+2mlpAAABdQwAAo0NMzkM/Uc5bQFVVd0NV1bFDAN9IP/e+W0BVVZNDAADOQweQUD9GUVtAVdWbQ6sq2UOjZVU/Kj1aQKsqo0NV1eNDNjVaP/JQV0BV1a1Dq6rzQ6i2Yj+z/U9AAACwQ1VV90MrNGc/6RBLQKuqs0MAgPxDlD9vP+kQS0BVVbRDq6r9Q5v9fD/pEEtAVVW0QwCA/EP6qow/6RBLQEABMhQNAACSQhUAAE1DHQAAkUMlAICXQ0CA6tvy3wcqjh4KEIy/wkwTg0bOsV7/ZXXyYYgSBggDEAEYBBoGCAAQARgAIAAqyh0KEEyUxz+ct0/zgUCHRMluPrERtFboNUAZx0EY6QEgByj4BzIQ6AMAAAAA3BMAAP9/AACAPzqQHauqykJVVbtDAAAAAAqkWkCrqtpCAICzQ8gaqDz/JV1Aq6oCQ6uqn0PYNS89Iu5cQFVVLEMAAHFDdFiQPQarXUBVVTtDq6pUQ4Y8sj0NpFxAVVVMQ1VVNkNME9U9bR1aQAAAWUNVVSFDDrz2PVsFVkAAAGFDq6oWQ3T3DD7aglFAVVVlQ1VVEUOuFh8+6RBLQKuqaUNVVQxDKoswPukQS0Crqm1DAAAJQ7/8QT7pEEtAAABxQ1VVB0Nu5VI+6RBLQKuqdEOrqgVDT55pPukQS0BVVX5DVVUDQy45gj7pEEtAv9KBQ9ivA0Oouoo+6RBLQKsqhEOrqgRDbfWTPukQS0BV1YlDq6oVQ3gEpT7GJE9AVVWOQwAANUNyGLY+GDBhQAAAkEOrqkpDF+m+PghVYUCrqotDVVXkQ9BFxz7QV2FAqyqLQ6uq5UPf0s8++F1hQAAAiENV1e1DjlLZPuSRYEBVVYNDVVX1QzxF4j4bqU9AVVVsQ1WVAEQvmfM+5qpOQAAAXEOragFE210CP9l7TEAAAFFDVdX9Q/MpCj+ea1JAAABLQwCA9kN35A4/NY1XQFVVQkNV1dpDyWMXPxvKWkBVVT9DVdXDQ+G9Gz+4SltAq6o+Q6uqtENQ+B8/QFxaQKuqQENV1aZDGVMkPy5nWUAAAERDVVWcQ4mCKD9FpFVAq6pHQ6uqlUNnsSw//URRQAAATkNV1Y5DoPUwP/JmTEBVVVFDAACNQ643NT/pEEtAAABaQ6sqikMMGz4/6RBLQCctX0Pj4YlDiy9GP+kQS0AAAGJDVdWJQ/xoSj/pEEtAAABmQ6uqikPbBlM/6RBLQKuqaENVVYtDXoBbP+kQS0DtJWpDE1qMQ1R7aD/pEEtApAxrQz8sjUOgQnA/6RBLQAAAbEMAAI5DBHF0P+kQS0CO42xDjuOPQ7K5eD/pEEtAAABuQwAAkkOd5H0/6RBLQKuqcEMAgJ5D4DCDP6dDUECrqnJDAICzQ3eJhz+Kz09Aq6pyQ1VVukNWtIk/D1hNQFVVcUMAgL5DPsuLP+kQS0BVVXBDqyrBQ9XzjT/pEEtAVVVvQwAAwkOwG5A/6RBLQKuqZEMAgMNDdTiUP+kQS0CrqkdDq6rCQznZmD/BsVFAAAAoQ1VVuUOTDJ0/NfBUQKuqCkNVVa1DZEWhPzAAVUBVVeVCAICiQ3IppT9wDFJAAADSQgCAnENuO6c/l+xPQAAAxkJV1ZZDdH6pP1p9TUAAALhCq6qOQ8ykrT/pEEtAq6q0QgAAi0NIx68/6RBLQKuqskIAgIdDOu2xP+kQS0BVVbFCAICDQ1Mutj/pEEtAq6qwQlVVgUMKUbg/6RBLQKuqskIAAHlDmHi8P+kQS0BVVbVCAAB1Qxz+vj/pEEtAAAC8QlVVbUOo/sI/6RBLQFVVwUJVVWlDS37FP+kQS0AAANBCAABiQxxhyT/pEEtAAADaQquqXUPfu8s/6RBLQFVV7UKrqlhDWcvPP+kQS0CrqvJCVVVXQ+TX0T/pEEtAq6oDQ6uqVEPZKNQ/6RBLQAAAD0NVVVNDKjbWP6WRS0CrqhpDVVVSQyWa2D/aN01AAAA2Q1VVUUPg5Nw/OLpOQKuqQENVVVJDOhPfP9P/TkCrqlxDVVVXQ2tO4z84b01AVVVoQ6uqWUOoduU/Vp1MQKuqe0NVVVxDGJvpP+kQS0BVVYFDAABdQ6DG6z/pEEtAq6qEQwAAXUNe+e8/6RBLQACAhkMAAFtDxiT0P+kQS0AAgIdDVVVSQ1gn+D/pEEtAVdWHQ1VVTEMTWfo/6RBLQKsqiEOrqkRDLnf8P+kQS0AAgIhDq6o+Q7PN/j/pEEtAqyqJQ6uqL0NNaAFA6RBLQKuqiUOrqihDLH0CQOkQS0BV1YlDAAAjQxm3A0DpEEtAVdWJQ1VVHUOMxgRA6RBLQFXViUOrqhhDbegFQOkQS0BV1YlDq6oSQ2j9BkDpEEtAVdWJQ1VVDENMCwhA6RBLQFXViUMAAAVDxR4JQOkQS0BV1YlDq6r6QtksCkDpEEtAVdWJQ1VV70ISOwtA6RBLQACAiUMAAORCOEcMQOkQS0BVVYlDx3HeQjNfDUDpEEtAqyqJQ1VV2UJUaQ5A6RBLQNeQiEOlodFCPGAQQOkQS0AAgIdDchzNQu6QE0DpEEtAuHGGQyfKy0K81hRA6RBLQKuqg0MAAM5C2cUWQGOQUEBV1YBDq6rWQsvcF0DJCFdAAABqQ6uqBkNMIxlAQDZaQAAAM0OrqkhDaD8bQJYOXUCrqh9Dq6pjQyROHEBOQVxAAAAaQ1VVa0MNYx1AElpaQKuq9kKrqotDGHQeQOZZWEAAAORCAICYQ7CQIEAETVdAAADgQlXVoUPsvSFAKbpTQAAA3kIAALFDQMMjQKkxV0BVVd9CVVW8Q7PdJEDMElpAVVXjQquqx0Mu6CVAl3dbQKuq5EKrqtlDCQEnQFOrXEBVVetCVdXyQ9sSKEAU9VtAVVXrQqvqC0QOMSpASF1ZQFVV60JV1Q1EbjsrQCLYVEBVVetCAMAQRJVXLECij0xAVVXrQlXVEkQRZC1A6RBLQFVV60JVVRNEZW8uQOkQS0AAAOxCq+oTREOcM0DpEEtAn/znQonoE0SnxDVA6RBLQFVV30JVFRNEHdE2QOkQS0BVVdFCAIAQRKchOEDxc1hAVVWrQqsqCETjLjpALg1fQKuqOkJVVcJDMVw8QFKDYUBVVSlCAACRQxl6PkApAmBAVVUxQquqa0OkhT9A7HldQFVVQUKrqkdDVptAQEnJWkCrqk5CVVU6Q1arQUCoaldAVVVhQlVVK0M8vkJAODxQQKuqZkKrqidDfttDQOkQS0BVVY9Cq6odQyJJRkC02UxAq6qqQquqFkMx3UdAOwBQQFVV0UIAAAxDhu9IQBdGUECrqvZCq6oBQygFSkD0xk5AVVUGQwAA+EKiEUtA8DNPQFVVDkOrqvBCPSNMQFttS0BVVRBDq6ruQsU4TUDpEEtAq6ocQ1VV40IAY05A6RBLQFVVI0MAAN5CPGlQQOkQS0BVVSVDTGjdQtuKUkDpEEtAAlonQ1oL3kIqnVNA6RBLQAAALEMAAORCZ65UQOkQS0CrqjJDVVXxQv2/VUDLqUxAVVU0QwAA9EIH+1ZAtFJQQAAAWEOrqhpD9/RYQNdQVECrqmRDVVUmQ7AEWkBNDlZAq6pvQ1VVMEPVF1tAav1UQKuqfEMAAD9D4SVcQLToUkAAAIRDVVVMQ3E4XUCKyVFAVdWHQ1VVVUNGSl5AyzBTQFVVjUNVVWJD64RfQI/OX0CrqpBDq6prQ4COYECjm19AAICUQ1XVgEP3qGFA/mNgQFVVlEOrKuRDy69iQHQyYUBV1ZJDVdXpQyzJY0AGkWFAq6qOQwCA+kOE0mRA4LJhQKsqhkNVlQdEXPRlQP3/WUBVVX5Dq+oMRJAIZ0C4n1lAAABsQ6tqEkTnHWhAo7tXQAAAYEMAABZENjVpQBcgVUCrqlpDqyoVRIhFakBLtFVAAABSQwBADkScWmxAWXJZQAAAT0NVVQZERHFtQDNhXEBVVUxDAAD9Q2qFbkBMT15AVVVOQwAA4UNWlm9Aj11fQAAAWENV1cdDkKZwQGT3XkCrqmpDq6quQ4q4cUCmlV5Aq6qAQwAAnEP7z3JA9uhcQFVVh0MAAJRDVuhzQLuUWkCrKphDqyqIQ7b3dUDRDlJAqyqfQ1VVh0PyEXdA6P9PQAAAoENVVYdDkSR4QKZwT0AAgKVDVdWKQ043eUA+qU1AAICoQ6sqkEPCTHpALohLQAAAq0MAAJlD81R7QAsDWkAAAKtDAICfQ8RffEB5FVxAVdWqQ6uqoEMEfH1AP9NbQFVVikMAgMpDa49+QCDmW0BVVW9Dq6rUQ8Kcf0BbSVxAVVVoQ6sq1UOnXIBA269cQAAAQUMAANZDRGWBQASaV0AAADZDAADQQ3wIgkCkclpAq6ooQ1XVrUNl/oJApVlbQKuqKkOrqplDHoqDQH+1W0AAADRDAICKQy0PhEC5lFlAq6o+QwAAf0OGmoRADBJWQAAASkMAAHBDth6FQG4CUEAAAE1Dq6puQyMzhkC6ak1AVVVOQ1VVcUP6u4ZAnQ9QQAAATkNVVYNDgkSHQKaBVUCrqklDAACPQ8LKh0DDA1ZAq6ozQ6uqrEMS4YhAoUlUQFVVLUMAALJDNu+JQIYzU0AAACpDVdWxQ/R8ikDHaFZAAAAiQ6uqrEOCAItA6mVYQFVVFkMAAJtDwIqLQKwIWUCrqhBDAAB/Q+YVjED8QFlAAAAQQwAAZENlnoxAGYlYQKuqEEMAAFhDTCaNQLgNVUBVVRNDAABMQ6MzjkARykxAAAAVQwAATEO4vI5Ade5UQFVVGkOrqlND4kSPQAPFWUCrqiVDq6pyQ9bSj0CCR1tAAAAzQ1XVkUOeWJBAPsRbQKuqO0NVVa5Dwt6QQOE2W0Crqj9DAIC8Q8JrkUAfH1lAq6pAQwAAwUOw8ZFAgxJVQAAAQUMAAMJDGvySQDPjUEBVVT9DAIC9Q8+Gk0BwgVpAAAA9Q1VVqkOZFZRAuTBdQAAAPUNVVZxD8p6UQCFSXkCrqlpDq6pXQ0MulUDIrl5AVVVuQwAAL0MiyZVAnWJdQKuqg0MAABJDAr+WQGezVkBV1YhDVVURQ8lDl0Dbb1VAAACMQwAAFEOaz5dANKNYQFXVjUMAACVDI1mYQFDqWUAAgI5DAABEQ5HjmECQ/FlAqyqOQwAAfUPFaZlAMzdaQKsqjEMAgJFDE/OZQJ4tWUCrqopDAACXQ7h6mkB8MFdAVdWIQ1XVm0PCBJtAF7VUQACAiEOrqpxDD4ybQBhhT0AAgIhDVdWXQ2ITnEB38E5AVdWJQ1VVh0M7nZxAUh9NQKuqi0MAAIFDtySdQPElTUCrqoxDq6p4Q9GsnUCbeEtAAnyNQxbVckNVSp9A6RBLQACAjUOrqndD1tSfQOkQS0AAgI1DVdWBQ3T/oEDpEEtAQAEyFA0AACRCFQAAyEIdAICXQyUAgPlDQMDDuLuwBzIUDQAAAAAVAAAAAB0AAAAAJQAAAAA6BggAEAAYAEIQ+sP/5uQ+QtS2sPZ02Jui7g=="
//        
//        guard let data = Data(base64Encoded: pkDrawingString) else {
//            return
//        }
//        
//        canvas.drawing = try! PKDrawing(data: data)
        
        
        let url = drawingFileURL()

        guard FileManager.default.fileExists(atPath: url.path) else {
            return
        }

        do {
            let data = try Data(contentsOf: url)
            let drawing = try PKDrawing(data: data)
            canvas.drawing = drawing
        } catch {
            print(error.localizedDescription)
        }
    }
    
    private func drawingFileURL() -> URL {
        let directory = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
        return directory.appendingPathComponent("drawing.pkdraw")
    }
}
